apps/entrada/urls.py
from django.conf.urls import url
from .views import EntradaListView, EntradaDetailView

urlpatterns = [
	url(r'^(?P<slug>[-\w]+)/$', EntradaDetailView.as_view(), name='entrada-detalle'),
	url(r'^$', EntradaListView.as_view(), name='entrada-listar'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from filebrowser.sites import site
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^articulos/', include('apps.entrada.urls', namespace='articulos')),
    url(r'^$', views.Index.as_view() ),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/entrada/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from tinymce.models import HTMLField

# Create your models here.
class Articulo(models.Model):
	titulo = models.CharField(max_length=200)
	fecha = models.DateTimeField()
	slug = models.SlugField(editable=False)
	contenido = HTMLField()

	def __str__(self):
		return self.titulo

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.titulo)
		super(Articulo, self).save(*args, **kwargs)

apps/entrada/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Articulo

# Create your views here.
class EntradaListView(ListView):
	model = Articulo
	template_name = 'entrada/index.html'

class EntradaDetailView(DetailView):
	model = Articulo	
	template_name = 'entrada/detalle.html'
	

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

## Vista Basada en clases
class Index(TemplateView):
	template_name = 'inicio/index.html'

#Vista basada en funciones
def index(request):
	return render(request, 'inicio/index.html')

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	
	{% block meta %}
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	{% endblock meta %}
	
	<title>{% block titulo %}Document{% endblock titulo %}</title>
	
	{% block css %}
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% endblock css %}

</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12">
				<nav class="navbar navbar-inverse">
					<div class="navbar-header">
						<a href="/" class="navbar-brand">Blog</a>
					</div>
					<ul class="nav navbar-nav">
						<li><a href="/articulos/">Articulos</a></li>
						<li><a href="/admin/">Administracion</a></li>
						<li><a href="/admin/filebrowser/browse/">File Browse</a></li>
					</ul>
				</nav>

				{% block contenido %}
					<h2>Editame we :v</h2>
				{% endblock contenido %}

			</div>
		</div>
	</div>
	
	{% block js %}
	<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<script
			  src="https://code.jquery.com/jquery-3.1.1.min.js"
			  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
			  crossorigin="anonymous"></script>
	{% endblock js %}

</body>
</html>

templates/entrada/detalle.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block titulo %}Entrada - {{object.titulo}}{% endblock titulo %}

{% block contenido %}

	<div class="container">
		<div class="row">
			<div class="col-md-offset-2 col-md-8">
				<h1>{{object.titulo}}</h1>
				<time>{{object.fecha}}</time>
				<div>
					{{object.contenido|safe}}
				</div>
			</div>
		</div>
	</div>
	
{% endblock contenido %}

templates/entrada/index.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block titulo %}
	Entradas
{% endblock titulo %}

{% block contenido %}
	<div class="container">
		<div class="row">
			<div class="col-md-offset-2 col-md-8">
				<h1>Entradas Recientes</h1>
				{% if object_list %}
					{% for entrada in object_list %}
						<h2><a href="{% url 'articulos:entrada-detalle' entrada.slug %}">{{ entrada.titulo }}</a><span class="badge">{{ entrada.fecha }}</span></h2>
						<div>
							{{ entrada.contenido|safe|truncatechars:200  }}
						</div>
						<br>
					{% endfor %}
					<br>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock contenido %}

templates/inicio/index.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block titulo %}
	Inicio
{% endblock titulo %}

{% block contenido %}
	{{block.super}}
	<h1>Hola Mundo!</h1>
{% endblock contenido %}